services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    container_name: PCweb
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./.env:/var/www/.env
    depends_on:
      - db
    networks:
      - PCnetwork
    env_file:
      - .env

  db:
    image: mysql:5.7
    container_name: PCdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pc_root
      MYSQL_DATABASE: pcdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - PCdb:/var/lib/mysql
    networks:
      - PCnetwork

  phpmyadmin:
    build:
      context: ./docker/phpmyadmin
      dockerfile: Dockerfile
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: pc_root
    depends_on:
      - db
    networks:
      - PCnetwork

volumes:
  PCdb:

networks:
  PCnetwork:

