<?php
//並び替え
$_sort = array(
    1 => "販売日順",
    2 => "相場高い順",
    3 => "相場低い順",
    4 => "お気に入り数順",
);
//重心情報
$_gravity_point = array(
    1 => "表上",
    2 => "表中",
    3 => "表下",
    4 => "裏上",
    5 => "裏中",
    6 => "裏下",
);

$_gravity_to_english = array(
    "表上" => "up_front",
    "表中" => "center_front",
    "表下" => "down_front",
    "裏上" => "up_back",
    "裏中" => "center_back",
    "裏下" => "down_back",
)
?>